### ISSUE TITLE
Reduce size

### ISSUE THREAD

**Issue by ai** [ElemeFE/obsolete-webpack-plugin#2]
## Current Behavior

The current size of `obsolete-web` is 23 KB is too big for a small script to show a warning.

https://bundlephobia.com/result?p=obsolete-web@0.5.3

Here is a good reminder that JS size is more important than picture size:

![1_prvznizf9jq_qadf5lqhpa](https://user-images.githubusercontent.com/19343/51137993-49677000-1840-11e9-97e9-49d201fabd90.png)

## Expected Behavior

Be at least 5 KB.

## Detailed Description

@chikara-chan You can use [Size Limit](https://github.com/ai/size-limit) to find why `obsolete-web` is so big right now.

At least, you should remove `core-js` and other Babel runtime from this small script.

**Comment by chikara-chan** [comment]
![xl9e82fx](https://user-images.githubusercontent.com/13572030/51155919-3b533700-18b4-11e9-82d6-ae1f09082523.png)

I think there must be some misleading. Actually, the plugin will read file from `dist/obsolete.min.js` rather than bundling`cjs/obsolete.js`. The eventual size is around 4kb.

And we use `core-js` to ensure that the library works properly in all browser environment. With `loose` option and only partial syntax transform, it doesn't have a big impact.

**Comment by ai** [comment]
Perfect!
